name: Handle Release Events

on:
  release:
    types: [published]

jobs:
  handle-release-events:
    runs-on: ubuntu-latest
    steps:
    - name: Check Release Type
      if: github.event.release.prerelease == true
      run: echo "A release draft has been saved."

    - name: Check Release Published
      if: github.event.release.prerelease == false && github.event.action == 'published'
      run: echo "A release has been published."
